version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      #- run: xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox
      #- run: xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js
      - run:
          name: Publish app to Docker Hub
          command: |
            docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
            docker build -t $DOCKER_HUB_USER/angular-hero:latest .
            docker tag $DOCKER_HUB_USER/angular-hero:latest $DOCKER_HUB_USER/angular-hero:v0.0.1
            # docker tag $DOCKER_HUB_USER/angular-hero:v0.0.1 $DOCKER_HUB_USER/angular-hero:latest
            docker push $DOCKER_HUB_USER/angular-hero:v0.0.1
            docker push $DOCKER_HUB_USER_ID/angular-hero:latest